version: '3.4'

services:
  service1.api:
    image: ${DOCKER_REGISTRY-}service1api
    build:
      context: .
      dockerfile: src/Services/Service1.API/Dockerfile

  service2.api:
    image: ${DOCKER_REGISTRY-}service2api
    build:
      context: .
      dockerfile: src/Services/Service2.API/Dockerfile

  identitydata:
    image: mcr.microsoft.com/mssql/server:2017-latest
  
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/dentity.API/Dockerfile
    depends_on:
      - identitydata


  httpaggregator:
    image: ${DOCKER_REGISTRY-}httpaggregator
    build:
      context: .
      dockerfile: src/HttpAggregator/Dockerfile


  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: src/Services/WebStatus/Dockerfile

