version: '3.4'

services:
  service1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Service2Api=http://service2.api/
      - TokenOptions__Issuer=http://identity.api/
    ports:
      - "1518:80"

  service2.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TokenOptions__Issuer=http://identity.api/

    ports:
      - "1519:80"

  identitydata:
    container_name: identitydata
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      
      
    ports:
      - "5435:1433"
    volumes:
      - template-identitydata:/var/opt/mssql

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AuthDb=server=identitydata;database=AuthDb;uid=sa;password=Pass@word;
      - TokenOptions__Issuer=http://identity.api/
    ports:
      - "5105:80"
      - "5106:443"

  httpaggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Service2Api__BaseAddress=http://service2.api/
      - TokenOptions__Issuer=http://identity.api/

    ports:
      - "1818:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Microservice1 HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://service1.api/hc
       - HealthChecksUI__HealthChecks__1__Name=Microservice2 HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://service2.api/hc
      - HealthChecksUI__HealthChecks__2__Name=Web Shopping Aggregator Gateway HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://httpaggregator/hc
      - HealthChecksUI__HealthChecks__3__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://identity.api/hc

    ports:
      - "8090:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  school.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
volumes:
  template-identitydata:
    external: false


