version: '3.4'

services:
  service1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  service2.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

